name: Build
on:
  push:
    paths-ignore:
      - 'CHANGELOG.md'
      - 'build.gradle'
      - '.release-please-manifest.json'
    branches:
      - master
      - hotfix/**
jobs:
  build:
    runs-on: macos-13
    permissions:
      contents: write
      id-token: write
      packages: read
    timeout-minutes: 40
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Docker on macOS
        uses: douglascamata/setup-docker-macos-action@v1-alpha

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build Java project
        run: ./gradlew build

