name: Build
on:
  push:
    paths-ignore:
      - 'CHANGELOG.md'
      - 'build.gradle.kts'
      - 'decimal4kmp/build.gradle.kts'
      - '.release-please-manifest.json'
      - '.github/**'
      - '**.md'
    branches:
      - main
      - hotfix/**
jobs:
  build:
    runs-on: macos-26
    permissions:
      contents: write
      id-token: write
      packages: read
    timeout-minutes: 40
    steps:
      - name: Checkout project
        uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build Java project
        run: ./gradlew check

  release:
    runs-on: runs-on=${{ github.run_id }}/runner=4cpu-linux-x64/image=${{ vars.GHA_IMAGE }}/spot=false/family=${{ vars.GHA_RUNNER_FAMILY }}/env=${{ vars.GHA_ENVIRONMENT }}/volume=${{ vars.GHA_RUNNER_DISK_SIZE }}/extras=s3-cache
    if: ${{ startsWith(github.ref_name, 'main') || startsWith(github.ref_name, 'hotfix') }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ secrets.APP_GITHUB_ID }}
          private-key: ${{ secrets.APP_GITHUB_PRIVATE_KEY }}

      - name: Release-please
        uses: googleapis/release-please-action@v5
        id: release
        with:
          token: ${{ steps.generate_token.outputs.token }}
          target-branch: ${{ github.ref_name }}
          path: ${{ inputs.path }}
