name: Build
on:
  push:
    paths-ignore:
      - 'CHANGELOG.md'
      - 'build.gradle'
      - '.release-please-manifest.json'
    branches:
      - master
      - hotfix/**
jobs:
  build:
    runs-on: ${{ vars.RUNNER_GITHUB_TYPE }}
    permissions:
      contents: write
      id-token: write
      packages: read
    timeout-minutes: 40
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Docker on macOS
        uses: douglascamata/setup-docker-macos-action@v1-alpha

      - name: Login to GAR
        uses: sundayapp/reusable-workflows/.github/actions/login-gcp@v3.5.0 # x-release-please-version
        with:
          workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDP }}
          service_account: ${{ vars.GCP_GITHUB_ACTIONS_SA_NAME }}

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build Java project
        run: ./gradlew build

