name: Release

on:
  push:
    paths:
      - 'CHANGELOG.md'
    branches:
      - master
      - hotfix/**

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref_name, 'master') || startsWith(github.ref_name, 'hotfix') }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_GITHUB_ID }}
          private_key: ${{ secrets.APP_GITHUB_PRIVATE_KEY }}

      - name: Release-please
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ steps.generate_token.outputs.token }}
          target-branch: ${{ github.ref_name }}
          path: ${{ inputs.path }}
